### ISSUE TITLE
Destination search under accomodation error

### ISSUE THREAD

**Issue by deepu552000** [TratokToken/smart-contracts#19]
<img width="960" alt="vf_2" src="https://user-images.githubusercontent.com/46034389/50311763-c57bcb80-04bf-11e9-9258-16b1d4928135.png">
After searching some place etc.. the values get shown and stuck on webpage. pls check to clear it once search tabbed out. check image.

**Comment by TratokToken** [comment]
Thanks for raising this issue. It is a current stopgap for the prototype and will be beautified shortly.

**Comment by deepu552000** [comment]
oh k then fine.. thanks :)
