### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by deepu552000** [TratokToken/smart-contracts#20]
<img width="960" alt="vf_3" src="https://user-images.githubusercontent.com/46034389/50342197-8b500f80-053b-11e9-8cc0-13304ea0b7eb.png">
I had uploaded a image for my profile. Image was uploaded but its in reversed side. pls check if this is normal.
my id : deepu552000@gmail.com

**Comment by TratokToken** [comment]
Firstly, let me congratulate you, your family look adorable.
Secondly, I will check into this shortly. Thanks for reporting it.

**Comment by deepu552000** [comment]
Thanks for compliment :)

Y R Sandeep
