### ISSUE TITLE
Sign Up 

### ISSUE THREAD

**Issue by deepu552000** [TratokToken/smart-contracts#21]
Signup button is not visible in main page. Looks it got moved now behind.
better if its visible to user.
<img width="960" alt="vf_4" src="https://user-images.githubusercontent.com/46034389/50372563-0bcd4980-05ea-11e9-8777-b31858d8b543.png">

**Comment by TratokToken** [comment]
Thanks for the report. 
Please bear with us, we are changing styles/font sizes and element positions trying to find the best responsive fix. We hope the end product is very nice.

**Comment by TratokToken** [comment]
Please, could you take another look. Thanks
