### ISSUE TITLE
Uploading Profile picture

### ISSUE THREAD

**Issue by msb900** [TratokToken/smart-contracts#24]
I have uploaded my profile picture and it worked fine. So I uploaded a different picture and this worked perfect. However, when I uploaded the first picture again. I received the message as in the screenshot saying that the profile picture is already uploaded. Option to choose from different profile pictures .. Edit/Remove ?

![screen shot 2018-12-23 at 10 54 47 am](https://user-images.githubusercontent.com/46082090/50381836-e56ae500-06a1-11e9-8c79-b4c1bc69f162.png)

**Comment by msb900** [comment]
If you upload the same picture with the same name anywhere in the website, this error will come up

**Comment by TratokToken** [comment]
This issue has been addressed. Please check again.
