### ISSUE TITLE
Booking Check-In & Check-Out Dates

### ISSUE THREAD

**Issue by msb900** [TratokToken/smart-contracts#26]
I booked a property where I put the check out date before the check in date and it accepted my booking where it should not. 

![screen shot 2018-12-23 at 11 08 16 am](https://user-images.githubusercontent.com/46082090/50381897-72fb0480-06a3-11e9-97ad-19b46665cf9b.png)

![screen shot 2018-12-23 at 11 11 38 am](https://user-images.githubusercontent.com/46082090/50381899-8e660f80-06a3-11e9-93b0-2a20675cdd1a.png)

**Comment by msb900** [comment]
Also, this property was pending verification in which booking should not be processed

**Comment by TratokToken** [comment]
Thank you, this issue has been corrected.
