### ISSUE TITLE
Searching for a cruise

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#29]
When choosing Cruises, there is no information, when it will be available. 
I wonder what I would search for then… Would I search for a cruise  line, a destination or the kind of cruise...? Think this needs to be different to thedDestination search.

The same applies for the activities.

**Comment by TratokToken** [comment]
This is due to a deal being concluded earlier than expected. We are currently implementing 12 different Mediterranean based cruises.
