### ISSUE TITLE
Tell a friend - ambassador

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#34]

**Comment by cliff67** [comment]
The referral link cannot be coppied.
And the link to the progamm terms does not work.

**Comment by cliff67** [comment]
I allready made the proposal to offer a downlaod along with the link that shows kind of a visitors card, that you can send where ever you want. Showing the referral link, your name with compliments and a link to the side with the explanations about Tratok.

**Comment by TratokToken** [comment]
We have added a copy button to make copying the link easier.
Our marketing team is working on this card and we will implement it as soon as we recieve the layout from them. Thanks for your suggestion.

**Comment by TratokToken** [comment]
The custodian is working on a video presentation which will be implemented at the end of the week.
