### ISSUE TITLE
Paying a booking

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#40]
How would it work, if I clicked pay. So my ewallet is available. Would I then be redirected to the ewallet?
Does Tratok offer there own ewallets that could be filled up in advance of a booking?

**Comment by TratokToken** [comment]
It will open up your metal mask wallet directly to the screen and ask you to approve the transaction. It will then redirect you automatically.

**Comment by cliff67** [comment]
Ich tried to click "I authorize payment" but nothing happend...

**Comment by TratokToken** [comment]
Did you have metamask plugin in your browser? If not did it prompt you to install it?

**Comment by cliff67** [comment]
No. I don´t habe the plugin and I wasn't asked to install it.  Nothing happend.

**Comment by TratokToken** [comment]
The second generation ecosystem has a clear Finance Centre in "Account Details". This acts as a users wallet in the ecosystem.
