### ISSUE TITLE
Message in the inbox

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#43]
1. If there is a message in s.o. inbox, there should be a notice to his email account. Elsewise it could be, that unread messages are not seen for a longer period.

2. The information about a booking would be much easier to understand, if it were in a list and not included into a written sentence...

3. I have a booking from Niklas Dalkowski. When I click on view bolings, it says that this booking has no association with me...

4. Further more, the boocked property was set inactive bevor the booking.

5. I have not understood so far, how the payment shall work. There is a price stated, but no information how to pay and to what address.

**Comment by TratokToken** [comment]
1.) We are impletmenting this feature.
2.) Noted we will make this more user friendly.
3.) Can you please provide a screenshot or booking number so we can investigate properly.
4.) We will look into this.
5.) It is automatic when you click the payment button.
