### ISSUE TITLE
Not compatibel with smartphone 

### ISSUE THREAD

**Issue by Backeljav** [TratokToken/smart-contracts#47]
Dear
![Screenshot_20190803_123255_com android chrome](https://user-images.githubusercontent.com/51862362/62410769-0f4a9980-b5eb-11e9-96fe-8a955ad8e9cb.jpg)
If you see at the picture then you see that its not possible to login. 
And some other feature also not possible with smartphone. 
There need to be beter possibility's with smartphone. 
Thx

**Comment by TratokToken** [comment]
This has been rectified in January 2020
