### ISSUE TITLE
Page too large on mobile

### ISSUE THREAD

**Issue by dhayor01** [TratokToken/smart-contracts#48]
![Screenshot_20190828-165235](https://user-images.githubusercontent.com/35843937/63871733-58a4c380-c9b4-11e9-86b0-85bb1bacbbbd.png)
This page is zoomed out on mobile. When you manage to fill in your details and paste your wallet address, it refuses to go back to other columns. 

Website : https://tratok.net/signup.php

**Comment by dhayor01** [comment]
Website: https://tratok.net/signup.php

**Comment by TratokToken** [comment]
This was addressed and fixed in V 1.1
