### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by ashishkumawat101** [TratokToken/smart-contracts#49]
I had 10,000 TRAT and I hold them for long-term. One day I saw they have changed contract address so I contact in telegram community but they just booked me after asking the question. Than I went to twitter they block me there also. 

Please guys be aware such projects they are here only to grab mony by fooling people.

**Comment by TratokToken** [comment]
Hello Ashish,

First of all we do not block feedback on social media, whether positive or negative. We believe in full transparency, hence why your comment here is not deleted.

In response to your reporting of "an issue", let us address the points:

1.) You were not blocked on twitter. Please present truths and responsible facts, not falsehoods.
2.) Telegram is run by community volunteers. I have checked the admin logs and seen that you were indeed removed after the following actions:
i.) You joined the Telegram and asked how to remove your bonus balance on the Tratok.net travel ecosystem.
ii.) The community volunteers politely pointed out to you that as per the terms you read and agreed to when signing up that were were for the purpose of travel.
iii.) You then proceeded to insult them and were removed.
Such behaviour is not acceptable in the community chat, which is there to forward development.

3.) In response to your scam accusations, I suggest you read the whitepaper and company financials. Tratok is a privately funded project and has never ever conducted a token sale, nor has the team ever sold a single token. All wallets are in the public domain at : https://tratok.com/transparency-and-values/

If you feel a team that has spent over USD 4 million of its own money to build a product and partnerships and never taken a single penny from the public is a clever way to grab money by fooling people, then there is nothing we can do from our part to help you. Such confusion is baffling.

We understand that you may have joined the program with "throw away" social media account and failed to follow updates over the last three years. As a result of this and not actually reading anything, we understand its infuriating to find our years later that the token has risen in value significantly. However, it was your own responsibility to read the terms and conditions, like thousands of others did correctly.

Good luck your future endeavors, 

Tratok Community Support
