### ISSUE TITLE
Please test the reset password feature

### ISSUE THREAD

**Issue by TratokToken** [TratokToken/smart-contracts#6]
Community, please test the reset password feature

**Comment by cliff67** [comment]
When I click reset password, it says URL not found

**Comment by deepu552000** [comment]
When we click reset password below is error 
 
Not Found
The requested URL /zebu/login_test.php was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by TratokToken** [comment]
This has been fixed. Thank you for the assistance.

**Comment by deepu552000** [comment]
I got the password reset link and new password. Able to login with it now.
But I don't find any option on site to change this password, as normally as a user we want to change default password. Can you pls advise where was that option ?

**Comment by TratokToken** [comment]
In the account settings page (View/Edit Settings), there is a button on the bottom left of the screen. Please try it and confirm.

**Comment by deepu552000** [comment]
I checked it.. working fine. able to change my password and login back..
thx team :)
