### ISSUE TITLE
Verify account

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#7]
The Despription of the possibility B shows some typos.

**Comment by deepu552000** [comment]
Also when we click verify account it doesn't show close option. we need to refresh page so it goes away.
chk attached image
<img width="960" alt="vf_1" src="https://user-images.githubusercontent.com/46034389/50311182-b09e3880-04bd-11e9-989d-66880f4a7287.png">

**Comment by TratokToken** [comment]
Both of these have been addressed and fixed. Thank you both for testing.

**Comment by deepu552000** [comment]
The issue is fine, great team for fixing issues so proactively. :)
