### ISSUE TITLE
Searching for accomodation

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#8]
The result of a search cannot be seen instantly. You need to scroll down fist - this should be changed, as you dont't expect this. Thus you think it doesn't work...
See below the result view after clicking search.

![image](https://user-images.githubusercontent.com/45995467/50217242-77b07780-0388-11e9-959e-d051659b8549.png)

**Comment by TratokToken** [comment]
This has been changed. Thanks for the feedback.
