### ISSUE TITLE
Booking an accomodation

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#9]
The number of adults or children is not ported from the search form to the booking table.

**Comment by cliff67** [comment]
The contact bottom at the booking confirmation does not work

**Comment by cliff67** [comment]
Cannot see a link to go back from my booking to the description of the hotel/room. Should be installed.

**Comment by cliff67** [comment]
I don't understand the system behind the statement.
Which one do I have to pay? Net payment or total cost?
Maybe that should be a bit clearer?
![image](https://user-images.githubusercontent.com/45995467/50218056-ebec1a80-038a-11e9-922f-d49bb8742445.png)

**Comment by TratokToken** [comment]
Excellent feedback, we will work on this shortly. Thank you again.

**Comment by TratokToken** [comment]
Thank you, we had addressed these issues and added a feature where you can see the room details on the same page. We believe this is easier than going back. Please let us know your opinion. Thanks.
